apiVersion: apps/v1
kind: Deployment
metadata:
  name: bingwee23
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bingwee23
  template:
    metadata:
      labels:
        app: bingwee23
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: bingwee23
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8ecf48f3-6a33-4994-99f0-cc53199124ad"
        - name: Vless_Path
          value: "/wgbe2374"
        - name: Vmess_UUID
          value: "8ecf48f3-6a33-4994-99f0-cc53199124ad"
        - name: Vmess_Path
          value: "/wgbe2374"
        - name: Share_Path
          value: "/v2link"
