apiVersion: v1
kind: Service
metadata:
  name: bingwee23
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "bingwee23"
    port: 8080
  selector:
    app: bingwee23
